server:
  port: 30940

nats:
  urls: nats://nats-service.default.svc.cluster.local:4222
  username:
  password:

management.security.enabled: false

endpoints:
  enabled: false
  health:
    enabled: true
    mapping.UNKNOWN: SERVICE_UNAVAILABLE
  info.enabled: true
  metrics.enabled: true

spring:
  mail:
    host: 10.2.14.1
    port: 25
    username: apasika@cybervisiontech.com
    password: Blablabla1
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true
  mvc:
    locale: en_US

epr:
  service:
    instance:
      name: ${eprInstanceName:epr_instance_1}

epts:
  service:
    instance: ${eptsInstanceName:epts_instance_1}

tsre:
  mailing:
    target-email: pasika2012@ukr.net
  nats:
    subject:
      protocol-version: v1
      scr-to-svc-protocol-version: v1
      targeted:
        service:
          config-refresh: kaa.${tsre.nats.subject.scr-to-svc-protocol-version}.service.${spring.application.name}.scr2svc.config-refresh
      events:
        metadata-event-prefix: kaa.${tsre.nats.subject.protocol-version}.events.${epr.service.instance.name}.endpoint.metadata
        endpoint-metadata-updated-event: ${tsre.nats.subject.events.metadata-event-prefix}.updated
        time-series-received-event-prefix: kaa.${tsre.nats.subject.protocol-version}.events.${epts.service.instance}.endpoint.data-collection.time-series-received
        time-series-names:
          - Temperature
          - Revolutions
          - Oil

logging:
  config: classpath:spring-logback.xml